### ISSUE TITLE
audioread.NoBackendError on Travis

### ISSUE THREAD

**Issue by carlthome** [beetbox/audioread#44]
The following .travis.yml produces an audioread.NoBackendError when LibROSA tries to open a Ogg file with audioread.

```yml
dist: trusty
language: python
python: 3.6
cache: pip
addons:
  apt:
    packages:
      - libav-tools
install: pip install librosa
script: 
  - python -c "import librosa; librosa.load(librosa.util.example_audio_file())"
```
